name: Called workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
        
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Hello $USERNAME"
        env:
          USERNAME: ${{ inputs.username }}
